### ISSUE TITLE
Widget disappear after adding

### ISSUE THREAD

**Issue by andrii482** [psifidotos/paneltransparencybutton#6]
![image](https://user-images.githubusercontent.com/61418776/121340750-9d4ee400-c928-11eb-883b-6d351d74073d.png)
![image](https://user-images.githubusercontent.com/61418776/121340820-b22b7780-c928-11eb-8410-3c51ab3d664d.png)
but when I try to edit panel - its appear:
![image](https://user-images.githubusercontent.com/61418776/121341029-f0289b80-c928-11eb-81d2-6a8fc484f5ac.png)

**Comment by psifidotos** [comment]
This is how it is intended to work.
You enable/disable it only in plasma edit mode.

**Comment by andrii482** [comment]
not really.
here - "edit mode" not enabled , but with some reason - I see widget buttons
![image](https://user-images.githubusercontent.com/61418776/121692487-ce6a1880-cad0-11eb-9d82-233eb5ac44be.png)

**Comment by psifidotos** [comment]
Oh, so it broke with Plasma 5.22

Unfortunately I am not interested in maintaining that applet any more.

**Comment by cipricus** [comment]
> Unfortunately I am not interested in maintaining that applet any more.

So posting about issues here is pointless, right?

**Comment by cipricus** [comment]
> Oh, so it broke with Plasma 5.22

Oddly, in my case it is always visible in 5.18.5 (Kubuntu LTS) but works as expected in 5.22 (Fedora). I think in 5.23 it stays visible (KaOS, don't have it installed now).

**Comment by cipricus** [comment]
> not really. here - "edit mode" not enabled , but with some reason - I see widget buttons ![image](https://user-images.githubusercontent.com/61418776/121692487-ce6a1880-cad0-11eb-9d82-233eb5ac44be.png)

From the image it seems that widget **stays always visible**, although **your title says the opposite**.

That's confusing. Maybe you mean **_"Widget doesn't disappear after adding"._**

Anyway: I'm pretty sure that what you mean is what I see in your image: the widget stays visible. The cause seems to be that our 5.18 starts behaving like an older version and needs the policy expected for older versions, namely _we have to lock the widgets for the button to get hidden_. The problem is that option was removed in 5.18.

For that we have a solution detailed [here](https://userbase.kde.org/Plasma/Tips#lock-widgets). I have also linked on reddit [here](https://www.reddit.com/r/kde/comments/ez4s32/comment/hkwqxoi/?utm_source=share&utm_medium=web2x&context=3).

The most elegant seems to me the installation of the widget[ Win7ShowDesktop ](https://store.kde.org/p/1100895/) which contains that option:

![image](https://user-images.githubusercontent.com/3447868/142075520-76e6bf96-195c-4f9a-b7bf-d71e4a2e1a54.png)

Oddly, here again I had to install  the **version for plasma 5.12 of Win7ShowDesktop widget** because the one for 5.18 was not working (probably for the same reasons for which the transparency button stays visible: our 5.18 acts like older versions).

After that the transparency button becomes invisible: but in the future **you will have to use the above option to unlock if you want to change the panel.**

**Comment by cipricus** [comment]
> Oh, so it broke with Plasma 5.22
> 
> Unfortunately I am not interested in maintaining that applet any more.

This is not 5.22, but 5.18 with an odd case of 5.18 behaving like older versions (where widgets have to be locked for transparency button to be hidden - which is not obvious in 5.18 and later, but is [possible](https://www.reddit.com/r/kde/comments/ez4s32/comment/hkwqxoi/?utm_source=share&utm_medium=web2x&context=3)).

**Comment by cipricus** [comment]
> Oh, so it broke with Plasma 5.22

I think not. In fact it works exactly as intended in 5.23. Where it doesn't it can be fixed by locking widgets (as said in my other comment).

**Comment by andrii482** [comment]
I don't know why, but problem - disappeared

**Comment by cipricus** [comment]
> I don't know why, but problem - disappeared

What's your Plasma version now?

In my experience the button stays visible (outside panel edit mode and needs locked widgets) in Plasma versions 5.18 and 5.24, while it behaves as expected (visible only in panel edit mode) in 5.22 and 5.23.
